const obey = require('../lib/models')

const model = obey.model({
  name: { type: 'string', required: true },
  permissions: { type: 'array', default: [], values: { type: 'string' } },
  created: { type: 'string', creator: 'timestamp' }, // automatically generated by `creator`
  modified: { type: 'string', modifier: 'timestamp' } // automatically updated by `modifier`
})

module.exports = {
  collection: 'roles',
  model
}
