const obey = require('../lib/models')
const argon2 = require('argon2')

const salt = new Buffer(process.env.AUTH_PASSWORD_SALT)
obey.modifier('encrypt', val => val ? argon2.hash(val, salt) : undefined)

const model = obey.model({
  fname: { type: 'string', required: true },
  lname: { type: 'string', required: true },
  email: { type: 'email', required: true },
  password: { type: 'string', modifier: 'encrypt', required: true },
  created: { type: 'string', creator: 'timestamp' }, // automatically generated by `creator`
  modified: { type: 'string', modifier: 'timestamp' } // automatically updated by `modifier`
})

module.exports = {
  collection: 'users',
  model
}
